version: '2'
services:
  web:
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.php:/apps/index.php
    ports:
      - 8080:80
  fpm:
    image: mario21ic/fpm:alpine
    build:
      context: ./
    volumes:
      - ./index.php:/apps/index.php
